smite_api.get_match_history(["Fallstand", 10])
[
    {
      "ActiveId1": 7672,
      "ActiveId2": 14536,
      "Active_1": "Aegis Amulet",
      "Active_2": "Belt of Frenzy",
      "Active_3": null,
      "Assists": 9,
      "Ban1": "Zeus",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 1672,
      "Ban2": "Persephone",
      "Ban2Id": 3705,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 92,
      "Damage": 7516,
      "Damage_Bot": 52535,
      "Damage_Done_In_Hand": 5015,
      "Damage_Mitigated": 4250,
      "Damage_Structure": 3385,
      "Damage_Taken": 10446,
      "Damage_Taken_Magical": 1797,
      "Damage_Taken_Physical": 8649,
      "Deaths": 3,
      "Distance_Traveled": 281642,
      "First_Ban_Side": "Winner",
      "God": "Izanami",
      "GodId": 2179,
      "Gold": 11482,
      "Healing": 0,
      "Healing_Bot": 0,
      "Healing_Player_Self": 3206,
      "ItemId1": 15490,
      "ItemId2": 14855,
      "ItemId3": 9626,
      "ItemId4": 9236,
      "ItemId5": 12668,
      "ItemId6": 0,
      "Item_1": "Evolved Hunter's Blessing",
      "Item_2": "Rage",
      "Item_3": "Warrior Tabi",
      "Item_4": "Bloodforge",
      "Item_5": "8-Pointed Shuriken",
      "Item_6": "",
      "Killing_Spree": 3,
      "Kills": 5,
      "Level": 15,
      "Map_Game": "Season 7 Joust 3v3",
      "Match": 1043461830,
      "Match_Queue_Id": 503,
      "Match_Time": "5/27/2020 3:01:07 AM",
      "Minutes": 17,
      "Multi_kill_Max": 1,
      "Objective_Assists": 3,
      "Queue": "Joust",
      "Region": "NA",
      "Skin": "Baroness",
      "SkinId": 16106,
      "Surrendered": 0,
      "TaskForce": 1,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 1037,
      "Wards_Placed": 3,
      "Win_Status": "Win",
      "Winning_TaskForce": 1,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    },
    {
      "ActiveId1": 7672,
      "ActiveId2": 14536,
      "Active_1": "Aegis Amulet",
      "Active_2": "Belt of Frenzy",
      "Active_3": null,
      "Assists": 1,
      "Ban1": "Zeus",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 1672,
      "Ban2": "Odin",
      "Ban2Id": 1669,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 199,
      "Damage": 10002,
      "Damage_Bot": 71833,
      "Damage_Done_In_Hand": 7050,
      "Damage_Mitigated": 5555,
      "Damage_Structure": 1800,
      "Damage_Taken": 12909,
      "Damage_Taken_Magical": 6401,
      "Damage_Taken_Physical": 6508,
      "Deaths": 2,
      "Distance_Traveled": 346572,
      "First_Ban_Side": "Loser",
      "God": "Izanami",
      "GodId": 2179,
      "Gold": 12202,
      "Healing": 0,
      "Healing_Bot": 0,
      "Healing_Player_Self": 1768,
      "ItemId1": 15490,
      "ItemId2": 15767,
      "ItemId3": 9627,
      "ItemId4": 7829,
      "ItemId5": 13427,
      "ItemId6": 12667,
      "Item_1": "Evolved Hunter's Blessing",
      "Item_2": "Transcendence",
      "Item_3": "Ninja Tabi",
      "Item_4": "Brawler's Beat Stick",
      "Item_5": "Poisoned Star ",
      "Item_6": "Shuriken",
      "Killing_Spree": 1,
      "Kills": 1,
      "Level": 17,
      "Map_Game": "Season 7 Joust 3v3",
      "Match": 1043450728,
      "Match_Queue_Id": 503,
      "Match_Time": "5/27/2020 2:29:05 AM",
      "Minutes": 21,
      "Multi_kill_Max": 1,
      "Objective_Assists": 2,
      "Queue": "Joust",
      "Region": "NA",
      "Skin": "Baroness",
      "SkinId": 16106,
      "Surrendered": 0,
      "TaskForce": 1,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 1311,
      "Wards_Placed": 7,
      "Win_Status": "Loss",
      "Winning_TaskForce": 2,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    },
    {
      "ActiveId1": 7672,
      "ActiveId2": 14536,
      "Active_1": "Aegis Amulet",
      "Active_2": "Belt of Frenzy",
      "Active_3": null,
      "Assists": 7,
      "Ban1": "Zeus",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 1672,
      "Ban2": "Bacchus",
      "Ban2Id": 1809,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 110,
      "Damage": 24874,
      "Damage_Bot": 70260,
      "Damage_Done_In_Hand": 18055,
      "Damage_Mitigated": 6422,
      "Damage_Structure": 3393,
      "Damage_Taken": 14391,
      "Damage_Taken_Magical": 3435,
      "Damage_Taken_Physical": 10956,
      "Deaths": 1,
      "Distance_Traveled": 300965,
      "First_Ban_Side": "Winner",
      "God": "Izanami",
      "GodId": 2179,
      "Gold": 12613,
      "Healing": 0,
      "Healing_Bot": 0,
      "Healing_Player_Self": 2261,
      "ItemId1": 15490,
      "ItemId2": 7829,
      "ItemId3": 9626,
      "ItemId4": 14855,
      "ItemId5": 7575,
      "ItemId6": 7573,
      "Item_1": "Evolved Hunter's Blessing",
      "Item_2": "Brawler's Beat Stick",
      "Item_3": "Warrior Tabi",
      "Item_4": "Rage",
      "Item_5": "The Executioner",
      "Item_6": "Light Blade",
      "Killing_Spree": 7,
      "Kills": 8,
      "Level": 17,
      "Map_Game": "Season 7 Joust 3v3",
      "Match": 1043440607,
      "Match_Queue_Id": 503,
      "Match_Time": "5/27/2020 2:01:07 AM",
      "Minutes": 18,
      "Multi_kill_Max": 1,
      "Objective_Assists": 3,
      "Queue": "Joust",
      "Region": "NA",
      "Skin": "Baroness",
      "SkinId": 16106,
      "Surrendered": 0,
      "TaskForce": 1,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 1102,
      "Wards_Placed": 2,
      "Win_Status": "Win",
      "Winning_TaskForce": 1,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    },
    {
      "ActiveId1": 8879,
      "ActiveId2": 14536,
      "Active_1": "Purification Beads",
      "Active_2": "Belt of Frenzy",
      "Active_3": null,
      "Assists": 6,
      "Ban1": "Aphrodite",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 1898,
      "Ban2": "Heimdallr",
      "Ban2Id": 3812,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 115,
      "Damage": 22656,
      "Damage_Bot": 71583,
      "Damage_Done_In_Hand": 5657,
      "Damage_Mitigated": 6779,
      "Damage_Structure": 310,
      "Damage_Taken": 20916,
      "Damage_Taken_Magical": 11195,
      "Damage_Taken_Physical": 9721,
      "Deaths": 8,
      "Distance_Traveled": 422002,
      "First_Ban_Side": "Winner",
      "God": "Vulcan",
      "GodId": 1869,
      "Gold": 15931,
      "Healing": 0,
      "Healing_Bot": 0,
      "Healing_Player_Self": 7494,
      "ItemId1": 0,
      "ItemId2": 8551,
      "ItemId3": 9634,
      "ItemId4": 12670,
      "ItemId5": 9128,
      "ItemId6": 7600,
      "Item_1": "",
      "Item_2": "Bancroft's Talon",
      "Item_3": "Shoes of Focus",
      "Item_4": "Spear of Desolation",
      "Item_5": "Soul Reaver",
      "Item_6": "Rod of Tahuti",
      "Killing_Spree": 3,
      "Kills": 7,
      "Level": 19,
      "Map_Game": "Season 7 Joust 3v3",
      "Match": 1043087360,
      "Match_Queue_Id": 503,
      "Match_Time": "5/26/2020 2:56:45 AM",
      "Minutes": 26,
      "Multi_kill_Max": 1,
      "Objective_Assists": 0,
      "Queue": "Joust",
      "Region": "NA",
      "Skin": "Full Metal",
      "SkinId": 14114,
      "Surrendered": 1,
      "TaskForce": 2,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 1600,
      "Wards_Placed": 5,
      "Win_Status": "Loss",
      "Winning_TaskForce": 1,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    },
    {
      "ActiveId1": 7672,
      "ActiveId2": 14536,
      "Active_1": "Aegis Amulet",
      "Active_2": "Belt of Frenzy",
      "Active_3": null,
      "Assists": 6,
      "Ban1": "Chaac",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 1966,
      "Ban2": "Aphrodite",
      "Ban2Id": 1898,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 140,
      "Damage": 11901,
      "Damage_Bot": 91207,
      "Damage_Done_In_Hand": 763,
      "Damage_Mitigated": 6013,
      "Damage_Structure": 0,
      "Damage_Taken": 15176,
      "Damage_Taken_Magical": 4348,
      "Damage_Taken_Physical": 10828,
      "Deaths": 3,
      "Distance_Traveled": 420868,
      "First_Ban_Side": "Loser",
      "God": "Kukulkan",
      "GodId": 1677,
      "Gold": 13705,
      "Healing": 0,
      "Healing_Bot": 0,
      "Healing_Player_Self": 5055,
      "ItemId1": 15483,
      "ItemId2": 7597,
      "ItemId3": 9634,
      "ItemId4": 7832,
      "ItemId5": 14080,
      "ItemId6": 9851,
      "Item_1": "Evolved Mage's Blessing",
      "Item_2": "Polynomicon",
      "Item_3": "Shoes of Focus",
      "Item_4": "Divine Ruin",
      "Item_5": "Book of the Dead",
      "Item_6": "Enchanted Spear",
      "Killing_Spree": 1,
      "Kills": 1,
      "Level": 18,
      "Map_Game": "Season 7 Joust 3v3",
      "Match": 1043075802,
      "Match_Queue_Id": 503,
      "Match_Time": "5/26/2020 2:24:45 AM",
      "Minutes": 24,
      "Multi_kill_Max": 1,
      "Objective_Assists": 0,
      "Queue": "Joust",
      "Region": "NA",
      "Skin": "Polar Vortex",
      "SkinId": 16091,
      "Surrendered": 0,
      "TaskForce": 1,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 1470,
      "Wards_Placed": 3,
      "Win_Status": "Loss",
      "Winning_TaskForce": 2,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    },
    {
      "ActiveId1": 8879,
      "ActiveId2": 18307,
      "Active_1": "Purification Beads",
      "Active_2": "Vision Shard",
      "Active_3": null,
      "Assists": 3,
      "Ban1": "Anubis",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 1668,
      "Ban2": "Zeus",
      "Ban2Id": 1672,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 44,
      "Damage": 4079,
      "Damage_Bot": 18431,
      "Damage_Done_In_Hand": 1342,
      "Damage_Mitigated": 2551,
      "Damage_Structure": 0,
      "Damage_Taken": 8842,
      "Damage_Taken_Magical": 1249,
      "Damage_Taken_Physical": 7551,
      "Deaths": 4,
      "Distance_Traveled": 161010,
      "First_Ban_Side": "Loser",
      "God": "Chiron",
      "GodId": 2075,
      "Gold": 6965,
      "Healing": 539,
      "Healing_Bot": 0,
      "Healing_Player_Self": 2411,
      "ItemId1": 15490,
      "ItemId2": 8547,
      "ItemId3": 9626,
      "ItemId4": 7573,
      "ItemId5": 0,
      "ItemId6": 0,
      "Item_1": "Evolved Hunter's Blessing",
      "Item_2": "Transcendence",
      "Item_3": "Warrior Tabi",
      "Item_4": "Light Blade",
      "Item_5": "",
      "Item_6": "",
      "Killing_Spree": 1,
      "Kills": 2,
      "Level": 11,
      "Map_Game": "Season 7 Joust 3v3",
      "Match": 1043062719,
      "Match_Queue_Id": 503,
      "Match_Time": "5/26/2020 1:48:45 AM",
      "Minutes": 10,
      "Multi_kill_Max": 1,
      "Objective_Assists": 0,
      "Queue": "Joust",
      "Region": "NA",
      "Skin": "Centaurion",
      "SkinId": 18582,
      "Surrendered": 1,
      "TaskForce": 1,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 614,
      "Wards_Placed": 3,
      "Win_Status": "Loss",
      "Winning_TaskForce": 2,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    },
    {
      "ActiveId1": 8879,
      "ActiveId2": 9041,
      "Active_1": "Purification Beads",
      "Active_2": "Meditation Cloak",
      "Active_3": null,
      "Assists": 4,
      "Ban1": "Anubis",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 1668,
      "Ban2": "Odin",
      "Ban2Id": 1669,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 119,
      "Damage": 12547,
      "Damage_Bot": 56672,
      "Damage_Done_In_Hand": 1269,
      "Damage_Mitigated": 2864,
      "Damage_Structure": 134,
      "Damage_Taken": 10070,
      "Damage_Taken_Magical": 6974,
      "Damage_Taken_Physical": 2331,
      "Deaths": 3,
      "Distance_Traveled": 293880,
      "First_Ban_Side": "Loser",
      "God": "Kukulkan",
      "GodId": 1677,
      "Gold": 11788,
      "Healing": 231,
      "Healing_Bot": 0,
      "Healing_Player_Self": 2312,
      "ItemId1": 15483,
      "ItemId2": 7597,
      "ItemId3": 9634,
      "ItemId4": 7784,
      "ItemId5": 12670,
      "ItemId6": 9858,
      "Item_1": "Evolved Mage's Blessing",
      "Item_2": "Polynomicon",
      "Item_3": "Shoes of Focus",
      "Item_4": "Chronos' Pendant",
      "Item_5": "Spear of Desolation",
      "Item_6": "Spellbook",
      "Killing_Spree": 3,
      "Kills": 5,
      "Level": 16,
      "Map_Game": "Season 7 Joust 3v3",
      "Match": 1042713946,
      "Match_Queue_Id": 503,
      "Match_Time": "5/25/2020 4:00:49 AM",
      "Minutes": 18,
      "Multi_kill_Max": 1,
      "Objective_Assists": 1,
      "Queue": "Joust",
      "Region": "NA",
      "Skin": "Polar Vortex",
      "SkinId": 16091,
      "Surrendered": 0,
      "TaskForce": 1,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 1086,
      "Wards_Placed": 2,
      "Win_Status": "Loss",
      "Winning_TaskForce": 2,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    },
    {
      "ActiveId1": 14146,
      "ActiveId2": 14538,
      "Active_1": "Purification Beads Upgrade",
      "Active_2": "Belt of Frenzy Upgrade",
      "Active_3": null,
      "Assists": 11,
      "Ban1": "Anubis",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 1668,
      "Ban2": "Zeus",
      "Ban2Id": 1672,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 111,
      "Damage": 18623,
      "Damage_Bot": 75722,
      "Damage_Done_In_Hand": 8619,
      "Damage_Mitigated": 6412,
      "Damage_Structure": 2724,
      "Damage_Taken": 20331,
      "Damage_Taken_Magical": 9177,
      "Damage_Taken_Physical": 11154,
      "Deaths": 5,
      "Distance_Traveled": 352967,
      "First_Ban_Side": "Winner",
      "God": "Artemis",
      "GodId": 1748,
      "Gold": 15723,
      "Healing": 0,
      "Healing_Bot": 0,
      "Healing_Player_Self": 3005,
      "ItemId1": 15490,
      "ItemId2": 12674,
      "ItemId3": 9627,
      "ItemId4": 13427,
      "ItemId5": 7575,
      "ItemId6": 7574,
      "Item_1": "Evolved Hunter's Blessing",
      "Item_2": "Wind Demon",
      "Item_3": "Ninja Tabi",
      "Item_4": "Poisoned Star ",
      "Item_5": "The Executioner",
      "Item_6": "Balanced Blade",
      "Killing_Spree": 4,
      "Kills": 10,
      "Level": 19,
      "Map_Game": "Season 7 Joust 3v3",
      "Match": 1042703149,
      "Match_Queue_Id": 503,
      "Match_Time": "5/25/2020 3:28:45 AM",
      "Minutes": 21,
      "Multi_kill_Max": 2,
      "Objective_Assists": 4,
      "Queue": "Joust",
      "Region": "NA",
      "Skin": "Dread Captain",
      "SkinId": 17619,
      "Surrendered": 0,
      "TaskForce": 1,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 1319,
      "Wards_Placed": 2,
      "Win_Status": "Win",
      "Winning_TaskForce": 1,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    },
    {
      "ActiveId1": 8879,
      "ActiveId2": 18307,
      "Active_1": "Purification Beads",
      "Active_2": "Vision Shard",
      "Active_3": null,
      "Assists": 7,
      "Ban1": "ChangE",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 1921,
      "Ban2": "Ah_Puch",
      "Ban2Id": 2056,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 111,
      "Damage": 7068,
      "Damage_Bot": 63933,
      "Damage_Done_In_Hand": 4821,
      "Damage_Mitigated": 2538,
      "Damage_Structure": 2550,
      "Damage_Taken": 6778,
      "Damage_Taken_Magical": 3008,
      "Damage_Taken_Physical": 3770,
      "Deaths": 2,
      "Distance_Traveled": 241301,
      "First_Ban_Side": "Loser",
      "God": "Izanami",
      "GodId": 2179,
      "Gold": 10749,
      "Healing": 0,
      "Healing_Bot": 0,
      "Healing_Player_Self": 2643,
      "ItemId1": 15490,
      "ItemId2": 9236,
      "ItemId3": 9627,
      "ItemId4": 7545,
      "ItemId5": 7573,
      "ItemId6": 0,
      "Item_1": "Evolved Hunter's Blessing",
      "Item_2": "Bloodforge",
      "Item_3": "Ninja Tabi",
      "Item_4": "Deathbringer",
      "Item_5": "Light Blade",
      "Item_6": "",
      "Killing_Spree": 3,
      "Kills": 3,
      "Level": 15,
      "Map_Game": "Season 7 Joust 3v3",
      "Match": 1042693449,
      "Match_Queue_Id": 503,
      "Match_Time": "5/25/2020 3:00:47 AM",
      "Minutes": 15,
      "Multi_kill_Max": 1,
      "Objective_Assists": 4,
      "Queue": "Joust",
      "Region": "NA",
      "Skin": "Baroness",
      "SkinId": 16106,
      "Surrendered": 0,
      "TaskForce": 2,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 923,
      "Wards_Placed": 3,
      "Win_Status": "Win",
      "Winning_TaskForce": 2,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    },
    {
      "ActiveId1": 7672,
      "ActiveId2": 14536,
      "Active_1": "Aegis Amulet",
      "Active_2": "Belt of Frenzy",
      "Active_3": null,
      "Assists": 6,
      "Ban1": "",
      "Ban10": "",
      "Ban10Id": 0,
      "Ban1Id": 0,
      "Ban2": "",
      "Ban2Id": 0,
      "Ban3": "",
      "Ban3Id": 0,
      "Ban4": "",
      "Ban4Id": 0,
      "Ban5": "",
      "Ban5Id": 0,
      "Ban6": "",
      "Ban6Id": 0,
      "Ban7": "",
      "Ban7Id": 0,
      "Ban8": "",
      "Ban8Id": 0,
      "Ban9": "",
      "Ban9Id": 0,
      "Creeps": 74,
      "Damage": 8601,
      "Damage_Bot": 27994,
      "Damage_Done_In_Hand": 3940,
      "Damage_Mitigated": 1868,
      "Damage_Structure": 2380,
      "Damage_Taken": 4610,
      "Damage_Taken_Magical": 1190,
      "Damage_Taken_Physical": 3420,
      "Deaths": 1,
      "Distance_Traveled": 153333,
      "First_Ban_Side": "",
      "God": "Artemis",
      "GodId": 1748,
      "Gold": 8293,
      "Healing": 0,
      "Healing_Bot": 0,
      "Healing_Player_Self": 1250,
      "ItemId1": 15490,
      "ItemId2": 15767,
      "ItemId3": 9627,
      "ItemId4": 7828,
      "ItemId5": 0,
      "ItemId6": 0,
      "Item_1": "Evolved Hunter's Blessing",
      "Item_2": "Transcendence",
      "Item_3": "Ninja Tabi",
      "Item_4": "Heavy Mace",
      "Item_5": "",
      "Item_6": "",
      "Killing_Spree": 2,
      "Kills": 3,
      "Level": 16,
      "Map_Game": "Clash",
      "Match": 1042306935,
      "Match_Queue_Id": 466,
      "Match_Time": "5/24/2020 3:39:37 AM",
      "Minutes": 10,
      "Multi_kill_Max": 1,
      "Objective_Assists": 1,
      "Queue": "Clash",
      "Region": "NA",
      "Skin": "Dread Captain",
      "SkinId": 17619,
      "Surrendered": 1,
      "TaskForce": 1,
      "Team1Score": 0,
      "Team2Score": 0,
      "Time_In_Match_Seconds": 614,
      "Wards_Placed": 2,
      "Win_Status": "Win",
      "Winning_TaskForce": 1,
      "playerId": 702429765,
      "playerName": "Fallstand",
      "ret_msg": null
    }
  ]

#   [{"Ability1":null,"Ability2":null,"Ability3":null,"Ability4":null,"Ability5":null,"AbilityId1":0,"AbilityId2":0,"AbilityId3":0,"AbilityId4":0,"AbilityId5":0,"Ability_1":null,"Ability_2":null,"Ability_3":null,"Ability_4":null,"Ability_5":null,"AttackSpeed":0,"AttackSpeedPerLevel":0,"Cons":null,"HP5PerLevel":0,"Health":0,"HealthPerFive":0,"HealthPerLevel":0,"Lore":null,"MP5PerLevel":0,"MagicProtection":0,"MagicProtectionPerLevel":0,"MagicalPower":0,"MagicalPowerPerLevel":0,"Mana":0,"ManaPerFive":0,"ManaPerLevel":0,"Name":null,"OnFreeRotation":null,"Pantheon":null,"PhysicalPower":0,"PhysicalPowerPerLevel":0,"PhysicalProtection":0,"PhysicalProtectionPerLevel":0,"Pros":null,"Roles":null,"Speed":0,"Title":null,"Type":null,"abilityDescription1":null,"abilityDescription2":null,"abilityDescription3":null,"abilityDescription4":null,"abilityDescription5":null,"basicAttack":null,"godAbility1_URL":null,"godAbility2_URL":null,"godAbility3_URL":null,"godAbility4_URL":null,"godAbility5_URL":null,"godCard_URL":null,"godIcon_URL":null,"id":0,"latestGod":null,"ret_msg":"Invalid session id."}]